Fix version handling: versions are now counted correctly; unsigned packages can not prevent updates any more

diff --git a/bin/bbrun b/bin/bbrun
--- a/bin/bbrun
+++ b/bin/bbrun
@@ -13,10 +13,34 @@ dst=`mktemp -d`
 # unpack to tmp
 cp "$1" $dst/p.tar.gz
 cd "$dst"
+tar xf p.tar.gz version
+
+# check version
+if [ -w "/etc" ]; then
+	versions=/etc/bashbundle/versions
+else
+	versions=~/.bashbundle/versions
+fi
+mkdir -p $versions
+
+vfile="$versions/`basename "$1"`.version"
+if [ -w "$vfile" ]
+then
+	if [ "`cat version`" -le "`cat "$vfile"`" ]
+	then
+		echo This Version is already installed
+		echo remove $vfile if you want to rerun
+		rm -rf "$dst" # cleanup
+		exit 3
+	fi
+fi
+
 tar xf p.tar.gz
 rm p.tar.gz
 
 function execute {
+  # update version
+  cp version "$vfile"
 	# unpack bundle
 	mkdir x
 	cd x
@@ -35,24 +59,6 @@ function execute {
 	rm -rf "$dst"
 }
 
-# check version
-if [ -w "/etc" ]; then
-	versions=/etc/bashbundle/versions
-else
-	versions=~/.bashbundle/versions
-fi
-mkdir -p $versions
-if [ -w "$versions/`basename "$1"`.version" ]
-then
-	vfile="$versions/`basename "$1"`.version"
-	if [ "`cat version`" -le "`cat "$vfile"`" ]
-	then
-		echo This Version is already installed
-		echo remove $vfile if you want to rerun
-		exit 3
-	fi
-fi
-cp version "$versions/`basename "$1"`.version"
 
 # check signature against keys
 (find "$pwd" -type f -iname "*.pem" -print0;
